name: Nextdoor Scanner

on:
  schedule:
    - cron: '0 1 * * *'  # 8:00 PM CT (1:00 AM UTC)
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb chromium-browser chromium-chromedriver
        sudo ln -sf /usr/bin/chromedriver /usr/local/bin/chromedriver
        pip install selenium beautifulsoup4 groq requests

    - name: Create keys file
      run: |
        if [ ! -z "${{ secrets.GROQ_API_KEY_1 }}" ]; then echo "${{ secrets.GROQ_API_KEY_1 }}" >> keys.txt; fi
        if [ ! -z "${{ secrets.GROQ_API_KEY_2 }}" ]; then echo "${{ secrets.GROQ_API_KEY_2 }}" >> keys.txt; fi
        if [ ! -z "${{ secrets.GROQ_API_KEY_3 }}" ]; then echo "${{ secrets.GROQ_API_KEY_3 }}" >> keys.txt; fi
        if [ ! -z "${{ secrets.GROQ_API_KEY_4 }}" ]; then echo "${{ secrets.GROQ_API_KEY_4 }}" >> keys.txt; fi
        if [ ! -z "${{ secrets.GROQ_API_KEY_5 }}" ]; then echo "${{ secrets.GROQ_API_KEY_5 }}" >> keys.txt; fi

    - name: Run scanner
      env:
        GITHUB_ACTIONS: true
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        BULQIT_EMAIL: ${{ secrets.BULQIT_EMAIL }}
        BULQIT_EMAIL_PASSWORD: ${{ secrets.BULQIT_EMAIL_PASSWORD }}
        DISPLAY: ':99'
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        sleep 3
        python3 nextdoor_complete.py